"""Add orders relationship to User

Revision ID: 1a70f0da1d1b
Revises: d1fa56d56e94
Create Date: 2024-11-30 16:08:23.025273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a70f0da1d1b'
down_revision: Union[str, None] = 'd1fa56d56e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
