"""update address and order model

Revision ID: 96dddf2fea00
Revises: a45ca758fe13
Create Date: 2024-12-01 14:08:27.435595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dddf2fea00'
down_revision: Union[str, None] = 'a45ca758fe13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'shipping_addresses', ['shipping_address_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'total_amount')
    op.add_column('shipping_addresses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('shipping_addresses', sa.Column('street', sa.String(), nullable=False))
    op.add_column('shipping_addresses', sa.Column('state', sa.String(), nullable=False))
    op.add_column('shipping_addresses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint('shipping_addresses_order_id_key', 'shipping_addresses', type_='unique')
    op.drop_constraint('shipping_addresses_order_id_fkey', 'shipping_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'shipping_addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shipping_addresses', 'address')
    op.drop_column('shipping_addresses', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_addresses', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shipping_addresses', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shipping_addresses', type_='foreignkey')
    op.create_foreign_key('shipping_addresses_order_id_fkey', 'shipping_addresses', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('shipping_addresses_order_id_key', 'shipping_addresses', ['order_id'])
    op.drop_column('shipping_addresses', 'created_at')
    op.drop_column('shipping_addresses', 'state')
    op.drop_column('shipping_addresses', 'street')
    op.drop_column('shipping_addresses', 'user_id')
    op.add_column('orders', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address_id')
    # ### end Alembic commands ###
