"""Add orders relationship to User

Revision ID: ae9767c43e9f
Revises: bfae3bfff44d
Create Date: 2024-11-30 16:33:22.414814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9767c43e9f'
down_revision: Union[str, None] = 'bfae3bfff44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
