"""Add orders relationship to User

Revision ID: bfae3bfff44d
Revises: 1a70f0da1d1b
Create Date: 2024-11-30 16:17:45.771971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfae3bfff44d'
down_revision: Union[str, None] = '1a70f0da1d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
